### PR TITLE
Sort themes by name

### PR DESCRIPTION
**Pull request by tbertels**
Current theme at the top

### CODE REVIEW

**Comment by georapbox** [comment]
Hey @tbertels, thanks for contributing. May I suggest some cosmetic changes, mostly for readability reasons?

First, we could distinguish the themes from the rest of the extensions using the `Array.prototype.filter` method.
```js
const themes = extensions.filter(extension => extension.type === 'theme');
```

and then for sorting, we could perform in place sorting like this:
```js
// Sort themes in place by enabled status, then by name.
// This puts the enabled theme at the top of the list
// and sorts the rest of the themes alphabetically.
themes.sort((a, b) => {
  if (a.enabled && !b.enabled) {
    return -1;
  } else if (!a.enabled && b.enabled) {
    return 1;
  } else {
    return a.name.localeCompare(b.name);
  }
});
```

The advantage of this approach overall, is that we avoid repetition of the same operations for the enabled theme and the rest. Therefore, the code becomes more compact.

Overall the solution would look something like this:

```js
browser.management.getAll().then(extensions => {
  const themes = extensions.filter(extension => extension.type === 'theme');

  // Sort themes in place by enabled status, then by name.
  // This puts the enabled theme at the top of the list
  // and sorts the rest of the themes alphabetically.
  themes.sort((a, b) => {
    if (a.enabled && !b.enabled) {
      return -1;
    } else if (!a.enabled && b.enabled) {
      return 1;
    } else {
      return a.name.localeCompare(b.name);
    }
  });

  for (const theme of themes) {
    const option = document.createElement('option');

    option.textContent = theme.name;
    option.title = theme.description;
    option.value = theme.id;

    if (theme.enabled) {
      option.selected = true;
    }

    themeSelect.appendChild(option);
  }
});
```

**Comment by tbertels** [comment]
Looks great, I wasn't a fan of the repetition either.

Apart from that, is there a reason to use
```
if (theme.enabled) {
  option.selected = true;
}
```
instead of
```
option.selected = theme.enabled;
```
?

**Comment by georapbox** [comment]
> Looks great, I wasn't a fan of the repetition either.
> 
> Apart from that, is there a reason to use
> 
> ```
> if (theme.enabled) {
>   option.selected = true;
> }
> ```
> 
> instead of
> 
> ```
> option.selected = theme.enabled;
> ```
> 
> ?

Good catch! No particular reason, I guess I never noticed before. Feel free to also change it. I would just ensure that the `option.selected` is always `true` by casting to Boolean, eg `option.selected = !!theme.enabled;`, although in this case it's already boolean but you know...

**Review by georapbox — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
